config/routes.rb
Rails.application.routes.draw do
  resources :hora_de_funcionamentos
  resources :dinners
  resources :lunches
  resources :breakfasts

  get 'menus/import', controller: 'menus', action: 'import', as: 'new_menus_import'
  resources :menus
  
  resources :customer_satisfactions

  get 'breakfast_satisfactions' => 'satisfactions_breakfast#index'
  get 'lunch_satisfactions' => 'satisfactions_lunch#index'
  get 'dinner_satisfactions' => 'satisfactions_dinner#index'
  get 'user_one_groups' => 'user_one_groups#index'
  get 'user_two_groups' => 'user_two_groups#index'
  get 'user_three_groups' => 'user_three_groups#index'

  root to: 'home#index'
  
  scope path: 'dashboard', as: 'dashboard' do
    get 'home', to: 'dashboard#index'
  end

  devise_for :users, skip: [:registrations]

  resources :users
  
  get 'charts', to: 'customer_satisfactions#charts'
end

app/models/hora_de_funcionamento.rb
class HoraDeFuncionamento < ApplicationRecord
end

app/controllers/hora_de_funcionamentos_controller.rb
class HoraDeFuncionamentosController < ApplicationController
  before_action :set_hora_de_funcionamento, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, only: [:index]

  # GET /hora_de_funcionamentos
  # GET /hora_de_funcionamentos.json
  def index
    @hora_de_funcionamentos = HoraDeFuncionamento.all
  end

  # GET /hora_de_funcionamentos/1
  # GET /hora_de_funcionamentos/1.json
  def show
  end

  # GET /hora_de_funcionamentos/new
  def new
    @hora_de_funcionamento = HoraDeFuncionamento.new
  end

  # GET /hora_de_funcionamentos/1/edit
  def edit
  end

  # POST /hora_de_funcionamentos
  # POST /hora_de_funcionamentos.json
  def create
    @hora_de_funcionamento = HoraDeFuncionamento.new(hora_de_funcionamento_params)

    respond_to do |format|
      if @hora_de_funcionamento.save
        format.html { redirect_to @hora_de_funcionamento, notice: 'Hora de funcionamento was successfully created.' }
        format.json { render :show, status: :created, location: @hora_de_funcionamento }
      else
        format.html { render :new }
        format.json { render json: @hora_de_funcionamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hora_de_funcionamentos/1
  # PATCH/PUT /hora_de_funcionamentos/1.json
  def update
    respond_to do |format|
      if @hora_de_funcionamento.update(hora_de_funcionamento_params)
        format.html { redirect_to @hora_de_funcionamento, notice: 'Hora de funcionamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @hora_de_funcionamento }
      else
        format.html { render :edit }
        format.json { render json: @hora_de_funcionamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hora_de_funcionamentos/1
  # DELETE /hora_de_funcionamentos/1.json
  def destroy
    @hora_de_funcionamento.destroy
    respond_to do |format|
      format.html { redirect_to hora_de_funcionamentos_url, notice: 'Hora de funcionamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hora_de_funcionamento
      @hora_de_funcionamento = HoraDeFuncionamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hora_de_funcionamento_params
      params.require(:hora_de_funcionamento).permit(:dia, :inicio, :fechamento)
    end
end

app/helpers/hora_de_funcionamentos_helper.rb
module HoraDeFuncionamentosHelper
end

app/views/hora_de_funcionamentos/_form.html.erb
<%= form_with(model: hora_de_funcionamento, local: true) do |form| %>
  <% if hora_de_funcionamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hora_de_funcionamento.errors.count, "error") %> prohibited this hora_de_funcionamento from being saved:</h2>

      <ul>
      <% hora_de_funcionamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia %>
    <%= form.date_select :dia, {:order => [:day, :month, :year]}%>
  </div>

  <div class="field">
    <%= form.label :inicio %>
    <%= form.time_select :inicio %>
  </div>

  <div class="field">
    <%= form.label :fechamento %>
    <%= form.time_select :fechamento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hora_de_funcionamentos/edit.html.erb
<h1>Editing Hora De Funcionamento</h1>

<%= render 'form', hora_de_funcionamento: @hora_de_funcionamento %>

<%= link_to 'Show', @hora_de_funcionamento %> |
<%= link_to 'Back', hora_de_funcionamentos_path %>

app/views/hora_de_funcionamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hora De Funcionamentos</h1>

<table>
  <thead>
    <tr>
      <th>Dia</th>
      <th>Inicio</th>
      <th>Fechamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hora_de_funcionamentos.each do |hora_de_funcionamento| %>
      <tr>
        <td><%= hora_de_funcionamento.dia %></td>
        <td><%= hora_de_funcionamento.inicio %></td>
        <td><%= hora_de_funcionamento.fechamento %></td>
        <td><%= link_to 'Show', hora_de_funcionamento %></td>
        <td><%= link_to 'Edit', edit_hora_de_funcionamento_path(hora_de_funcionamento) %></td>
        <td><%= link_to 'Destroy', hora_de_funcionamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hora De Funcionamento', new_hora_de_funcionamento_path %>

app/views/hora_de_funcionamentos/new.html.erb
<h1>New Hora De Funcionamento</h1>

<%= render 'form', hora_de_funcionamento: @hora_de_funcionamento %>

<%= link_to 'Back', hora_de_funcionamentos_path %>

app/views/hora_de_funcionamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @hora_de_funcionamento.dia %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @hora_de_funcionamento.inicio %>
</p>

<p>
  <strong>Fechamento:</strong>
  <%= @hora_de_funcionamento.fechamento %>
</p>

<%= link_to 'Edit', edit_hora_de_funcionamento_path(@hora_de_funcionamento) %> |
<%= link_to 'Back', hora_de_funcionamentos_path %>