config/routes.rb
Rails.application.routes.draw do
  resources :hora_de_funcionamentos
  resources :dinners
  resources :lunches
  resources :breakfasts

  get 'menus/import', controller: 'menus', action: 'import', as: 'new_menus_import'
  resources :menus
  
  resources :customer_satisfactions

  get 'breakfast_satisfactions' => 'satisfactions_breakfast#index'
  get 'lunch_satisfactions' => 'satisfactions_lunch#index'
  get 'dinner_satisfactions' => 'satisfactions_dinner#index'
  get 'user_one_groups' => 'user_one_groups#index'
  get 'user_two_groups' => 'user_two_groups#index'
  get 'user_three_groups' => 'user_three_groups#index'

  root to: 'home#index'
  
  scope path: 'dashboard', as: 'dashboard' do
    get 'home', to: 'dashboard#index'
  end

  devise_for :users, skip: [:registrations]

  resources :users
  
  get 'charts', to: 'customer_satisfactions#charts'
end

app/models/review_lunch.rb
##
# Essa classe aplica as validações de ReviewLunch
# ReviewLunch deve conter um rating e um comment e não podem ser nulos
# Deve existir um User e um Lunch
class ReviewLunch < ApplicationRecord
    belongs_to :user
    belongs_to :lunch

    validates :rating, :comment, presence: true
    validates :rating, numericality:{
        only_integer: true,
        greater_than_or_equal_to: 1,
        less_than_or_equal_to: 5,
        message: "Somente uma nota inteira entre 1 e 5"
    }
end

app/controllers/review_lunches_controller.rb
  ##
  # classe de controller das avaliações de um jantar.
class ReviewLunchesController < ApplicationController
  before_action :set_review_lunch, only: [:edit, :update, :destroy]
  before_action :set_lunch
  before_action :authenticate_user!

  ##
  # Esse método cria uma nova instância de ReviewLunches
  # ReviewLunches é composto dos campos:
  # user_id: User.id
  # rating: integer
  # comment: string
  # lunch_id: lunch.id
  def new
    @review_lunch = ReviewLunch.new
  end

  # GET /review_lunches/1/edit
  def edit
  end

  ##
  # Esse método cria uma nova instância de ReviewLunches e adiciona ao banco de dados.
  # Esse método também vincula um ReviewLunches a um Breakfast e a um User
  def create
    @review_lunch = ReviewLunch.new(review_lunch_params)
    @review_lunch.user_id = current_user.id
    @review_lunch.lunch_id = @lunch.id

    respond_to do |format|
      if @review_lunch.save
        format.html { redirect_to @lunch, notice: 'Review lunch was successfully created.' }
        format.json { render :show, status: :created, location: @review_lunch }
      else
        format.html { render :new }
        format.json { render json: @review_lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Esse método atualiza uma edição em um ReviewLunches
  # Podem ser atualizados os campos rating e comment.
  def update
    respond_to do |format|
      if @review_lunch.update(review_lunch_params)
        format.html { redirect_to @lunch, notice: 'Review lunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @review_lunch }
      else
        format.html { render :edit }
        format.json { render json: @review_lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Esse método remove um ReviewLunches do banco.
  # Caso ocorra com sucesso uma mensagem informa o usuário
  def destroy
    @review_lunch.destroy
    respond_to do |format|
      format.html { redirect_to @lunch, notice: 'Review lunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_lunch
      @review_lunch = ReviewLunch.find(params[:id])
    end

    def set_lunch
      @lunch = Lunch.find(params[:lunch_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_lunch_params
      params.require(:review_lunch).permit(:rating, :comment)
    end
end

app/helpers/review_lunches_helper.rb
module ReviewLunchesHelper
end

app/views/review_lunches/_form.html.erb
<%= form_with(model: review_lunch, url: [@lunch, @review_lunch]) do |form| %>
  <% if review_lunch.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button> 
      <h4><%= pluralize(review_lunch.errors.count, "error") %> prohibited this review_lunch from being saved:</h4>

      <ul>
      <% review_lunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '../../../assets',
    hints: ['terrível', 'ruim', 'normal', 'bom', 'excelente'],
    scoreName: 'review_lunch[rating]'
  });
</script>

app/views/review_lunches/edit.html.erb
<h1>Editing Review Lunch</h1>

<%= render 'form', review_lunch: @review_lunch %>

<%= link_to 'Back', lunch_path(@lunch)  %>

app/views/review_lunches/new.html.erb
<h1>New Review Lunch</h1>

<%= render 'form', review_lunch: @review_lunch %>

<%= link_to 'Back', lunch_path(@lunch)  %>