config/routes.rb
Rails.application.routes.draw do
  resources :hora_de_funcionamentos
  resources :dinners
  resources :lunches
  resources :breakfasts

  get 'menus/import', controller: 'menus', action: 'import', as: 'new_menus_import'
  resources :menus
  
  resources :customer_satisfactions

  get 'breakfast_satisfactions' => 'satisfactions_breakfast#index'
  get 'lunch_satisfactions' => 'satisfactions_lunch#index'
  get 'dinner_satisfactions' => 'satisfactions_dinner#index'
  get 'user_one_groups' => 'user_one_groups#index'
  get 'user_two_groups' => 'user_two_groups#index'
  get 'user_three_groups' => 'user_three_groups#index'

  root to: 'home#index'
  
  scope path: 'dashboard', as: 'dashboard' do
    get 'home', to: 'dashboard#index'
  end

  devise_for :users, skip: [:registrations]

  resources :users
  
  get 'charts', to: 'customer_satisfactions#charts'
end

app/controllers/customer_satisfactions_controller.rb
class CustomerSatisfactionsController < ApplicationController
  # Funções para serem realizadas antes de qualquer método do controlador
  # O only indica onde em quais métodos elas serão executadas antes
  # No caso a set_customer que é uma função para definir exatamente qual pesquisa
  # É chamada antes dos métodos show, edit, update e destroy
  # A segunda função é uma função padrão do devise que é chamada para verificar o usuario logado
  before_action :set_customer_satisfaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :charts]

  # Método Index é chamado de duas maneiras
  # O intuito dele é retornar todos as pesquisas feitas pelo usuário
  # A diferença é dada por qual formato ele será renderizado
  # Caso o admin queria ver somente pela web ele irá renderizar o formato html
  # Mas caso queria baixar a planilha, ele terá um formato pdf
  def index
     @customer_satisfactions = CustomerSatisfaction.order('rating DESC').all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "relatorio"   
      end
    end
  end

  # Método que é responsável por retornar um objeto
  # Esse objeto é os dados especificos de uma pesquisa
  def show
  end

  # Método que é chamado ao ir para a página de formulário de pesquisa
  # Ele é responsável por instanciar um novo objeto
  # Objeto que será utilizado em conjunto com o método create
  def new
    @customer_satisfaction = CustomerSatisfaction.new
  end

  # Método que retorna um objeto específico da pesquisa
  # trabalha em conjunto com o método update
  def edit
  end

  
  # Método chamado após o new
  # Ao passar os parametros uma novo pesquisa foi criada
  # Apos isso ele verifica se foi possível salvar o objeto no banco
  # Caso consigo ele voltará a chamar o método index
  # Caso contrário ele irá renderizar o método new
  def create
    @customer_satisfaction = CustomerSatisfaction.new(customer_satisfaction_params)
    if @customer_satisfaction.save
      redirect_to @customer_satisfaction, notice: 'Pesquisa de Satisfação criada com sucesso.'
    else
      render :new 
    end
  
  end

  # Trabalha em conjunto com método edit
  # Os parametros são passado e passando para um função update
  # Caso as alterações consigam ser salvas no banco ele voltará para a página do método index
  # Caso contrário irá chamar novamente a página do index edit
  def update
    if @customer_satisfaction.update(customer_satisfaction_params)
      redirect_to @customer_satisfaction, notice: 'Pesquisa de Satisfação atualizada com sucesso.'
    else
      render :edit
    end
    
  end

  # Método chamado para deletar um objeto no banco de dados
  # Ao terminar de apagar ele é redirecionado para a página que utiliza o index
  def destroy
    @customer_satisfaction.destroy
  
    redirect_to customer_satisfactions_url, notice: 'Pesquisa de Satisfação excluida com sucesso.'
  
  end

  # Método adiconal
  # Não está presente no Famoso CRUD do rails
  # Tem uma utilização específica no sistema
  # Ele é chamado ao se tentar ver a página de gráficos
  # São feitas 6 pesquisas no banco de dados para serem aplicadas em gráficos diferentes
  # Os três primeiros estão contando o total de acontecimentos nos atributos meal, rating e user_group
  # Os três últimos estão agrupando por usuário e realizando a contagem das notos dos usuários
  def charts
    @line_chart = CustomerSatisfaction.group(:meal).count
    @pie_chart = CustomerSatisfaction.group(:rating).count
    @column_chart = CustomerSatisfaction.group(:user_group).count


    @customer_by_rating_1 = CustomerSatisfaction.where(user_group: 1).group(:rating).count
    @customer_by_rating_2 = CustomerSatisfaction.where(user_group: 2).group(:rating).count
    @customer_by_rating_3 = CustomerSatisfaction.where(user_group: 3).group(:rating).count
  end

  # Método privado do controller
  # Não pode ser usado em outro controler
  # O Primerio método procura um objeto no banco de dados quando disponibilizado um id para a busca
  # O segundo está requisitando e verificando os parametros passado para o controller
  private
    def set_customer_satisfaction
      @customer_satisfaction = CustomerSatisfaction.find(params[:id])
    end

    def customer_satisfaction_params
      params.require(:customer_satisfaction).permit(:user_group, :meal, :rating, :like, :disgust, :suggestion)
    end
end

app/helpers/customer_satisfactions_helper.rb
module CustomerSatisfactionsHelper
end

app/views/customer_satisfactions/_form.html.erb
<%= form_with(model: customer_satisfaction, local: true) do |form| %>
  <% if customer_satisfaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_satisfaction.errors.count, "error") %> prohibited this customer_satisfaction from being saved:</h2>

      <ul>
      <% customer_satisfaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= form.label :user_group %>
    <%= form.select :user_group, ['1', '2', '3'] %>
  </div>

  <div class="form-group">
    <%= form.label :meal %>
    <%= form.select :meal, ['Almoco', 'Cafe', 'Janta'] %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, ['1', '2', '3', '4', '5'] %>
  </div>
  
  <div class="form-group">
    <%= form.label :like %>
    <%= form.text_area :like %>
  </div>

  <div class="form-group">
    <%= form.label :disgust %>
    <%= form.text_area :disgust %>
  </div>

  <div class="form-group">
    <%= form.label :suggestion %>
    <%= form.text_area :suggestion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_satisfactions/charts.html.erb
<h1>Quantidade de respostas por refeição</h1>
<%= line_chart @line_chart %>

<h1>Notas do usuários</h1>
<%= pie_chart @pie_chart %>

<h1>Grupo de usuário</h1>
<%= column_chart @column_chart %>

<h1>Nota por grupo de usuários 1</h1>
<%= column_chart @customer_by_rating_1 %>


<h1>Nota por grupo de usuários 2</h1>
<%= column_chart @customer_by_rating_2 %>

<h1>Nota por grupo de usuários 3</h1>
<%= column_chart @customer_by_rating_3 %>

app/views/customer_satisfactions/edit.html.erb
<h1>Editing Customer Satisfaction</h1>

<%= render 'form', customer_satisfaction: @customer_satisfaction %>

<%= link_to 'Show', @customer_satisfaction %> |
<%= link_to 'Back', customer_satisfactions_path %>

app/views/customer_satisfactions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Customer Satisfactions</h1>
  <h2> Listar por refeições: </h2>
  <div style="display:flex;">
      <p><%= link_to 'Café', breakfast_satisfactions_path, class:"btn btn-primary m-2"%></p>
      <p><%= link_to 'Almoço', lunch_satisfactions_path, class:"btn btn-primary m-2"%></p>
      <p><%= link_to 'Janta', dinner_satisfactions_path, class:"btn btn-primary m-2"%></p>
  </div>

  <h2> Listar por grupo de usuários: </h2>
  <div style="display:flex;">
      <p><%= link_to 'Grupo 1', user_one_groups_path, class:"btn btn-primary m-2"%></p>
      <p><%= link_to 'Grupo 2', user_two_groups_path, class:"btn btn-primary m-2"%></p>
      <p><%= link_to 'Grupo 3', user_three_groups_path	, class:"btn btn-primary m-2"%></p>
  </div>

  <table class="table table-striped">
    <thead style="background-color: #F28D3C; color: white;">
      <tr>
        <th>User group</th>
        <th>Meal</th>
        <th>Rating</th>
        <th>Like</th>
        <th>Disgust</th>
        <th>Suggestion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @customer_satisfactions.each do |customer_satisfaction| %>
        <tr>
          <td><%= customer_satisfaction.user_group %></td>
          <td><%= customer_satisfaction.meal %></td>
          <td><%= customer_satisfaction.rating %></td>
          <td><%= customer_satisfaction.like %></td>
          <td><%= customer_satisfaction.disgust %></td>
          <td><%= customer_satisfaction.suggestion %></td>
          <td><%= link_to 'Ver detalhes', customer_satisfaction,class:"btn btn-primary m-2" %></td>
          <!-- <td><%= link_to 'Edit', edit_customer_satisfaction_path(customer_satisfaction) %></td> !-->
          <td><%= link_to 'Apagar', customer_satisfaction, method: :delete,  class:"btn btn-danger m-2"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Gerar PDF', customer_satisfactions_path(format: :pdf),class:"btn btn-success" %>
  <%= link_to 'New Customer Satisfaction', new_customer_satisfaction_path, class:"btn btn-primary m-2" %>
</div>

app/views/customer_satisfactions/index.pdf.erb
<table>
  <thead>
    <tr>
      <th>User group</th>
      <th>Meal</th>
      <th>Rating</th>
      <th>Like</th>
      <th>Disgust</th>
      <th>Suggestion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_satisfactions.each do |customer_satisfaction| %>
      <tr>
        <td><%= customer_satisfaction.user_group %></td>
        <td><%= customer_satisfaction.meal %></td>
        <td><%= customer_satisfaction.rating %></td>
        <td><%= customer_satisfaction.like %></td>
        <td><%= customer_satisfaction.disgust %></td>
        <td><%= customer_satisfaction.suggestion %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/customer_satisfactions/new.html.erb
<h1>New Customer Satisfaction</h1>

<%= render 'form', customer_satisfaction: @customer_satisfaction %>

<%= link_to 'Back', customer_satisfactions_path %>

app/views/customer_satisfactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grupo:</strong>
  <%= @customer_satisfaction.user_group %>
</p>

<p>
  <strong>Refeição:</strong>
  <%= @customer_satisfaction.meal %>
</p>

<p>
  <strong>Avaliação:</strong>
  <%= @customer_satisfaction.rating %>
</p>

<p>
  <strong>Gostou de:</strong>
  <%= @customer_satisfaction.like %>
</p>

<p>
  <strong>Não gostou de:</strong>
  <%= @customer_satisfaction.disgust %>
</p>

<p>
  <strong>Sugestão:</strong>
  <%= @customer_satisfaction.suggestion %>
</p>

<!--<%= link_to 'Edit', edit_customer_satisfaction_path(@customer_satisfaction) %> | -->
<%= link_to 'voltar', customer_satisfactions_path %>