config/routes.rb
Rails.application.routes.draw do
  resources :hora_de_funcionamentos
  resources :dinners
  resources :lunches
  resources :breakfasts

  get 'menus/import', controller: 'menus', action: 'import', as: 'new_menus_import'
  resources :menus
  
  resources :customer_satisfactions

  get 'breakfast_satisfactions' => 'satisfactions_breakfast#index'
  get 'lunch_satisfactions' => 'satisfactions_lunch#index'
  get 'dinner_satisfactions' => 'satisfactions_dinner#index'
  get 'user_one_groups' => 'user_one_groups#index'
  get 'user_two_groups' => 'user_two_groups#index'
  get 'user_three_groups' => 'user_three_groups#index'

  root to: 'home#index'
  
  scope path: 'dashboard', as: 'dashboard' do
    get 'home', to: 'dashboard#index'
  end

  devise_for :users, skip: [:registrations]

  resources :users
  
  get 'charts', to: 'customer_satisfactions#charts'
end

app/models/breakfast.rb
class Breakfast < ApplicationRecord
  belongs_to :menu
  has_many :review_breakfast

  validates :menu_id, presence: true
  validates :hot_drinks, presence: true
  validates :vegetarian_drink, presence: true
  validates :chocolate_milk, presence: true
  validates :bread, presence: true
  validates :vegetarian_bread, presence: true
  validates :margarine, presence: true
  validates :vegetarian_margarine, presence: true
  validates :complement, presence: true
  validates :vegetarian_complement, presence: true
  validates :fruit, presence: true
end

app/controllers/breakfasts_controller.rb
class BreakfastsController < ApplicationController
  # Funções para serem realizadas antes de qualquer método do controlador
  # O only indica onde em quais métodos elas serão executadas antes
  # No caso a set_breakfast que é uma função para definir exatamente qual café da manhã
  # É chamada antes dos métodos show, edit, update e destroy
  # A segunda função é uma função padrão do devise que é chamada para verificar o usuario logado
  before_action :set_breakfast, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # Método index é chamado para ir à página onde todos os cafés da manhã registrdos são mostrados
  def index
    @breakfasts = Breakfast.all
  end

  # Método responsável por retornar os dados de um registro de café da manhã específico
  def show
    @review_breakfast = ReviewBreakfast.where(breakfast_id: @breakfast.id).order("created_at DESC")
    if @review_breakfast.blank?
      @avg_rating = 0
    else
      @avg_rating = @review_breakfast.average(:rating).round(2)
    end
  end

  # Método que é chamado ao ir para a página de cadastro de café da manhã
  # Ele é responsável por instanciar um novo objeto
  # Objeto que será utilizado em conjunto com o método create
  def new
    @breakfast = Breakfast.new
    @menus = Menu.all
  end

  # Método que retorna um objeto específico de café da manhã para ser editado
  # trabalha em conjunto com o método update
  def edit
  end

  # Método chamado após o new, para criar um novo café da manhã
  # Caso consigo ele voltará a chamar o método index
  # Caso contrário ele irá renderizar o método new
  def create
    @breakfast = Breakfast.new(breakfast_params)
      if @breakfast.save
        @menu = Menu.find(@breakfast.menu_id)
        redirect_to @menu, notice: 'Desjejum criado com sucesso'
      else
        render :new, locals: { :menu_id => :menu_id }
      end
  end

  # Trabalha em conjunto com método edit
  # Os parametros são passado e passando para um função update
  # Caso as alterações consigam ser salvas no banco ele voltará para a página do método index
  # Caso contrário irá chamar novamente a página do index edit
  def update
      if @breakfast.update(breakfast_params)
        @menu = Menu.find(@breakfast.menu_id)
        redirect_to @menu, notice: 'Desjejum atualizado com sucesso.'
      else
        render :edit, locals: { :menu_id => :menu_id }
      end
  end

  # Método chamado para deletar um objeto no banco de dados
  # Ao terminar de apagar ele é redirecionado para a página que utiliza o index
  def destroy
    begin
      @breakfast.destroy
      flash[:notice] = 'Desjejum excluido com sucesso'
      redirect_to breakfasts_url
    end
  end


  private
  # Método privado do controller
  # Não pode ser usado em outro controler
  # O método procura um objeto no banco de dados quando disponibilizado um id para a busca
    def set_breakfast
      @breakfast = Breakfast.find(params[:id])
    end
  # Método privado do controller
  # Não pode ser usado em outro controler
  # O método está requisitando e verificando os parametros passados para o controller
    def breakfast_params
      params.require(:breakfast).permit(:menu_id, :hot_drinks, :vegetarian_drink, :chocolate_milk, :bread, :vegetarian_bread, :margarine, :vegetarian_margarine, :complement, :vegetarian_complement, :fruit)
    end
end

app/helpers/breakfasts_helper.rb
module BreakfastsHelper
end

app/views/breakfasts/_form.html.erb
<%= form_with(model: breakfast, local: true) do |form| %>
  <% if breakfast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breakfast.errors.count, "error") %> prohibited this breakfast from being saved:</h2>

      <ul>
      <% breakfast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if params[:menu_id] %>
    <%= form.hidden_field :menu_id, :value => params[:menu_id] %>
  <% else %>
    <div class='form-group'>
      <%= form.label :menu_id, 'Dia do cardápio' %>
      <%= form.collection_select(:menu_id, Menu.all, :id, :date,  {},  {class: 'form-control'}) %>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :hot_drinks %>
    <%= form.text_field :hot_drinks %>
  </div>

  <div class="field">
    <%= form.label :vegetarian_drink %>
    <%= form.text_field :vegetarian_drink %>
  </div>

  <div class="field">
    <%= form.label :chocolate_milk %>
    <%= form.text_field :chocolate_milk %>
  </div>

  <div class="field">
    <%= form.label :bread %>
    <%= form.text_field :bread %>
  </div>

  <div class="field">
    <%= form.label :vegetarian_bread %>
    <%= form.text_field :vegetarian_bread %>
  </div>

  <div class="field">
    <%= form.label :margarine %>
    <%= form.text_field :margarine %>
  </div>

  <div class="field">
    <%= form.label :vegetarian_margarine %>
    <%= form.text_field :vegetarian_margarine %>
  </div>

  <div class="field">
    <%= form.label :complement %>
    <%= form.text_field :complement %>
  </div>

  <div class="field">
    <%= form.label :vegetarian_complement %>
    <%= form.text_field :vegetarian_complement %>
  </div>

  <div class="field">
    <%= form.label :fruit %>
    <%= form.text_field :fruit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breakfasts/edit.html.erb
<h1>Alterações no Café da Manhã</h1>

<%= render 'form', breakfast: @breakfast %>

<%= link_to 'Show', @breakfast %> |
<%= link_to 'Back', breakfasts_path %>

app/views/breakfasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breakfasts</h1>

<table>
  <thead>
    <tr>
      <th>Hot drinks</th>
      <th>Vegetarian drink</th>
      <th>Chocolate milk</th>
      <th>Bread</th>
      <th>Vegetarian bread</th>
      <th>Margarine</th>
      <th>Vegetarian margarine</th>
      <th>Complement</th>
      <th>Vegetarian complement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breakfasts.each do |breakfast| %>
      <tr>
        <td><%= breakfast.hot_drinks %></td>
        <td><%= breakfast.vegetarian_drink %></td>
        <td><%= breakfast.chocolate_milk %></td>
        <td><%= breakfast.bread %></td>
        <td><%= breakfast.vegetarian_bread %></td>
        <td><%= breakfast.margarine %></td>
        <td><%= breakfast.vegetarian_margarine %></td>
        <td><%= breakfast.complement %></td>
        <td><%= breakfast.vegetarian_complement %></td>
        <td><%= link_to 'Show', breakfast %></td>
        <td><%= link_to 'Edit', edit_breakfast_path(breakfast) %></td>
        <td><%= link_to 'Destroy', breakfast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breakfast', new_breakfast_path %>

app/views/breakfasts/new.html.erb
<h1>New Breakfast</h1>

<%= render 'form', breakfast: @breakfast %>

<%= link_to 'Back', breakfasts_path %>

app/views/breakfasts/show.html.erb
<p id="notice"><%= notice %></p>

<div class ="row">
  <div class="col-md-4">
    <h2>Café da manhã:</h2>
    <p>
      <strong>Hot drinks:</strong>
      <%= @breakfast.hot_drinks %>
    </p>

    <p>
      <strong>Vegetarian drink:</strong>
      <%= @breakfast.vegetarian_drink %>
    </p>

    <p>
      <strong>Chocolate milk:</strong>
      <%= @breakfast.chocolate_milk %>
    </p>

    <p>
      <strong>Bread:</strong>
      <%= @breakfast.bread %>
    </p>

    <p>
      <strong>Vegetarian bread:</strong>
      <%= @breakfast.vegetarian_bread %>
    </p>

    <p>
      <strong>Margarine:</strong>
      <%= @breakfast.margarine %>
    </p>

    <p>
      <strong>Vegetarian margarine:</strong>
      <%= @breakfast.vegetarian_margarine %>
    </p>

    <p>
      <strong>Complement:</strong>
      <%= @breakfast.complement %>
    </p>

    <p>
      <strong>Vegetarian complement:</strong>
      <%= @breakfast.vegetarian_complement %>
    </p>

    <p>
      <strong>Nota do cardápio:</strong>
      <div class="star-rating" data-rating= <%= @avg_rating %> ></div>
      <p> <%= " #{@review_breakfast.length} reviews" %> </p>
    </p>

    <%= link_to 'Dê sua opinião', new_breakfast_review_breakfast_path(@breakfast), class: "btn btn-primary" %>
  </div>

  <div class="col-md-8">
    <% if @review_breakfast.blank? %>
      <h3>Nenhuma opnião ainda. Seja o primeiro a compartilhar a sua!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>
        <tbody>
          <% @review_breakfast.each do |review_breakfast| %>
            <tr>
              <td>
                <h5>
                  <%="#{User.where(id: review_breakfast.user_id).first.email}" %>
                </h5>
                <p><%= review_breakfast.created_at.strftime("%-m/%-d/%-y") %></p>
              </td>
              <td>
                <div class = "star-rating" data-rating = <%= review_breakfast.rating %>></div>
                <p><%= h(review_breakfast.comment).gsub(/\n/,'<br/>').html_safe %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_breakfast_path(@breakfast), class: "btn btn-link"  %> |
<%= link_to 'Back', breakfasts_path, class: "btn btn-link"  %>

<script>
  $('.star-rating').raty({
    path: '../assets',
    noRatedMsg: 'Nunca mais!',
    hints: ['terrível', 'ruim', 'normal', 'bom', 'excelente'],
    readOnly: true,
    score: function(){
      return $(this).attr('data-rating');
    }
  });
</script>